#!/bin/bash
file_name=$1
if ! [ -f $file_name ]
then
	echo "No such file"
	exit 0
fi
if ! [ -d ~/.trash ];
then
	mkdir ~/.trash
fi
link_id="$(wc -l ~/.trash.log | cut -d ' ' -f 1)"
full_path="$(pwd)/$1"
ln $file_name ~/.trash/$link_id
echo "$full_path $link_id" >> ~/.trash.log
rm $file_name
